services:
  backend:
    build: ./backend
    container_name: demo-backend
    ports:
      - "7777:7777"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=public
      - SPRING_DATASOURCE_USERNAME=gaussdb
      - SPRING_DATASOURCE_PASSWORD=OpenGauss@123
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    container_name: demo-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  db:
    image: enmotech/opengauss:3.1.0
    container_name: demo-db
    environment:
      - GS_PASSWORD=OpenGauss@123
    privileged: true
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/opengauss/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
